### ISSUE TITLE
plugin fails to build with 3.1.0

### ISSUE THREAD

**Issue by klehigh** [sethhall/bro-myricom#8]
The configure script refers to bro-config, which fails.  

Also, the iosource changes appear to break the build process :

bro-myricom/src/Plugin.cc:10:34: error: no type named 'PktSrcComponent' in namespace 'iosource'
    AddComponent(new ::iosource::PktSrcComponent("MyricomReader", "myricom", ::iosource::PktSrcComponent::LIVE, ::iosource::pktsrc::MyricomSource::InstantiateM...

**Comment by klehigh** [comment]
Here is a hacked up configure script that should work w/ 3.0 and above.

https://gist.github.com/klehigh/e9bfb566f4707bd8e45b7ff37902f97d

**Comment by klehigh** [comment]
This is probably a better configure than mine : https://github.com/zeek/package-manager/blob/master/testing/packages/rot13/configure
